version: "3"
services:
  web:
    image: my-app-webpack
    volumes:
      - '.:/usr/src/app'
      - '/usr/src/app/node_modules'
    # command: webpack-dev-server --hot --inline --open --mode development
    ports:
      - '4000:8080'
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true